services:
  redis:
    image: redis
    ports:
      - 6379:6379
  db:
    image: mysql:5.7.41
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=tiger
      - MYSQL_DATABASE=tigerdb
      - MYSQL_USER=scott
      - MYSQL_PASSWORD=tiger
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
